--DEVICE_TYPE
INSERT INTO DEVICE_TYPE VALUES(1, 'Windows Desktop');
INSERT INTO DEVICE_TYPE VALUES(2, 'Mac Os');
INSERT INTO DEVICE_TYPE VALUES(3, 'Windows Server');
INSERT INTO DEVICE_TYPE VALUES(4, 'Linux Ubuntu');

--SERVICE
INSERT INTO SERVICE VALUES(1, 4.0, 'Base Device');
INSERT INTO SERVICE VALUES(2, 5.0, 'Antivirus');
INSERT INTO SERVICE VALUES(3, 3.0, 'Backup');
INSERT INTO SERVICE VALUES(4, 2.0, 'PSA');
INSERT INTO SERVICE VALUES(5, 1.0, 'Screen Share');

--DEVICE
INSERT INTO DEVICE VALUES(1, 'Lenovo Laptop',1);
INSERT INTO DEVICE VALUES(2, 'Macbook Pro',2);
INSERT INTO DEVICE VALUES(3, 'Asus All one',1);
INSERT INTO DEVICE VALUES(4, 'Dell Server',3);
INSERT INTO DEVICE VALUES(5, 'Hp x',4);

