INSERT INTO ITSERVICE(COST, DESCRIPTION, NAME) VALUES (4, 'Basic Fee for Any Device', 'DEVICE FEE');
INSERT INTO SERVICE_DEVICE_TYPES VALUES (1, 'ANY');
INSERT INTO DEVICE (SYSTEM_NAME, TYPE) VALUES('WINDOWS Personal 1', 'WINDOWS_WORKSTATION');
