INSERT INTO CUSTOMER VALUES('C1','Customer1');
INSERT INTO DEVICE_TYPE VALUES('DT1','MAC');
INSERT INTO DEVICE_TYPE VALUES('DT2','WINDOWS');
INSERT INTO DEVICE VALUES(1,'MacDevice1','DT1','C1');
INSERT INTO DEVICE VALUES(2,'MacDevice2','DT1','C1');
INSERT INTO DEVICE VALUES(3,'MacDevice3','DT1','C1');
INSERT INTO DEVICE VALUES(4,'WindowsDevice1','DT2','C1');
INSERT INTO DEVICE VALUES(5,'WindowsDevice2','DT2','C1');
INSERT INTO SERVICE_ONE VALUES('S0','Device Register');
INSERT INTO SERVICE_ONE VALUES('S1','Antivirus');
INSERT INTO SERVICE_ONE VALUES('S2','Backup');
INSERT INTO SERVICE_ONE VALUES('S3','PSA');
INSERT INTO SERVICE_ONE VALUES('S4','Screen Share');
INSERT INTO SERVICE_DEVICE_TYPE VALUES('SDT9',4.0,'DT1','S0');
INSERT INTO SERVICE_DEVICE_TYPE VALUES('SDT10',4.0,'DT2','S0');
INSERT INTO SERVICE_DEVICE_TYPE VALUES('SDT1',7.0,'DT1','S1');
INSERT INTO SERVICE_DEVICE_TYPE VALUES('SDT2',5.0,'DT2','S1');
INSERT INTO SERVICE_DEVICE_TYPE VALUES('SDT3',3.0,'DT1','S2');
INSERT INTO SERVICE_DEVICE_TYPE VALUES('SDT4',3.0,'DT2','S2');
INSERT INTO SERVICE_DEVICE_TYPE VALUES('SDT5',2.0,'DT1','S3');
INSERT INTO SERVICE_DEVICE_TYPE VALUES('SDT6',2.0,'DT2','S3');
INSERT INTO SERVICE_DEVICE_TYPE VALUES('SDT7',1.0,'DT1','S3');
INSERT INTO SERVICE_DEVICE_TYPE VALUES('SDT8',1.0,'DT2','S3');
INSERT INTO DEVICE_SERVICE_DEVICE_TYPE VALUES('DSDT16',1,'SDT9'); /*+1 MAC Registration fee*/
INSERT INTO DEVICE_SERVICE_DEVICE_TYPE VALUES('DSDT17',2,'SDT9'); /*+1 MAC Registration fee*/
INSERT INTO DEVICE_SERVICE_DEVICE_TYPE VALUES('DSDT18',3,'SDT9'); /*+1 MAC Registration fee*/
INSERT INTO DEVICE_SERVICE_DEVICE_TYPE VALUES('DSDT19',4,'SDT10'); /*+1 Windows Registration fee*/
INSERT INTO DEVICE_SERVICE_DEVICE_TYPE VALUES('DSDT20',5,'SDT10'); /*+1 Windows Registration fee*/
INSERT INTO DEVICE_SERVICE_DEVICE_TYPE VALUES('DSDT1',1,'SDT1'); /*+1 MAC antivirus */
INSERT INTO DEVICE_SERVICE_DEVICE_TYPE VALUES('DSDT2',2,'SDT1'); /*+1 MAC antivirus */
INSERT INTO DEVICE_SERVICE_DEVICE_TYPE VALUES('DSDT3',3,'SDT1'); /*+1 MAC antivirus */
INSERT INTO DEVICE_SERVICE_DEVICE_TYPE VALUES('DSDT4',4,'SDT2'); /*+1 Windows antivirus */
INSERT INTO DEVICE_SERVICE_DEVICE_TYPE VALUES('DSDT5',5,'SDT2'); /*+1 Windows antivirus */
INSERT INTO DEVICE_SERVICE_DEVICE_TYPE VALUES('DSDT6',1,'SDT3'); /*+1 MAC Backup */
INSERT INTO DEVICE_SERVICE_DEVICE_TYPE VALUES('DSDT7',2,'SDT3'); /*+1 MAC Backup */
INSERT INTO DEVICE_SERVICE_DEVICE_TYPE VALUES('DSDT8',3,'SDT3'); /*+1 MAC Backup */
INSERT INTO DEVICE_SERVICE_DEVICE_TYPE VALUES('DSDT9',4,'SDT4'); /*+1 Windows Backup */
INSERT INTO DEVICE_SERVICE_DEVICE_TYPE VALUES('DSDT10',5,'SDT4'); /*+1 Windows Backup */
INSERT INTO DEVICE_SERVICE_DEVICE_TYPE VALUES('DSDT11',1,'SDT7'); /*+1 MAC Screen Share */
INSERT INTO DEVICE_SERVICE_DEVICE_TYPE VALUES('DSDT12',2,'SDT7'); /*+1 MAC Screen Share*/
INSERT INTO DEVICE_SERVICE_DEVICE_TYPE VALUES('DSDT13',3,'SDT7'); /*+1 MAC Screen Share*/
INSERT INTO DEVICE_SERVICE_DEVICE_TYPE VALUES('DSDT14',4,'SDT8'); /*+1 Windows Screen Share*/
INSERT INTO DEVICE_SERVICE_DEVICE_TYPE VALUES('DSDT15',5,'SDT8'); /*+1 Windows Screen Share*/
